; PlatformIO project configuration - SweetHertz Deliverable 3
; Flora Farms Greenhouse Monitor: ESP32 + DHT22 + MQ-5 + LCD

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Required libraries
lib_deps =
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
  tobiasschuerg/ESP8266 Influxdb @ ^3.13.2
